"""Parent and child order schemas."""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, model_validator


class ExecutionSide(StrEnum):
    BUY = "buy"
    SELL = "sell"


class ParentOrder(BaseModel):
    """Parent order request for execution simulation."""

    model_config = ConfigDict(frozen=True)

    side: ExecutionSide
    symbol: str = Field(default="XYZ", min_length=1)
    quantity: int = Field(gt=0)
    start_time: int = Field(default=0, ge=0)
    end_time: int = Field(gt=0)
    limit_price: int | None = Field(default=None, gt=0)
    participation_limit: float | None = Field(default=None, gt=0, le=1)

    @model_validator(mode="after")
    def validate_times(self) -> ParentOrder:
        if self.end_time <= self.start_time:
            msg = "end_time must be greater than start_time"
            raise ValueError(msg)
        return self


class ChildOrder(BaseModel):
    """Child market order emitted by a strategy."""

    model_config = ConfigDict(frozen=True)

    child_order_id: str
    timestamp: int = Field(ge=0)
    symbol: str = Field(min_length=1)
    side: ExecutionSide
    quantity: int = Field(gt=0)
    strategy: str


class Fill(BaseModel):
    """Execution fill generated by the C++ matching engine."""

    model_config = ConfigDict(frozen=True)

    child_order_id: str
    trade_id: str
    timestamp: int
    symbol: str
    side: ExecutionSide
    price_ticks: int
    quantity: int
    maker_order_id: str


class ExecutionResult(BaseModel):
    """Serializable execution result."""

    model_config = ConfigDict(frozen=True)

    strategy: str
    parent_order: ParentOrder
    child_orders: list[ChildOrder]
    fills: list[Fill]
    requested_quantity: int
    realized_quantity: int
    unfilled_quantity: int
    average_fill_price_ticks: float | None
    fill_rate: float
    cost_notional_ticks: int
    synthetic: bool = True
